---
# Install and configure the NTP deamon

- name: ensure NTP daemon is installed
  ansible.builtin.package:
    name: "{{ __ntp_package }}"
    state: present
    update_cache: yes
  become: yes

- name: configure the NTP daemon
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  become: yes
  notify:
    - restart ntp
  tags:
    - ntp_config

- name: ensure NTP is running and enabled
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
  become: yes
  tags:
    - ntp_config
